# Generated by Django 4.2.4 on 2025-05-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0002_alter_tasks_content_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='online_status',
            new_name='visually_impaired',
        ),
    ]
