# Generated by Django 4.2.4 on 2025-05-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0003_rename_online_status_profile_visually_impaired'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
